### PR TITLE
2.3.1 - Typescript Config

### PR DESCRIPTION
**Pull request by sfaizanh**
I have update package.json for typescript build

### CODE REVIEW

**Comment by sfaizanh** [comment]
@arielfaur can you update me on this

**Comment by arielfaur** [comment]
@sfaizanh I just tried your changes but I still need to add the ```files``` array to the ```tsconfig.json``` otherwise I get the error below:
```
  "files": [
    "node_modules/ionic-audio/dist/index.ts"
  ]
```

If I remove the files array  I get:

```
Runtime Error
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\ariel\Projects\test-audio\node_modules\ionic-audio\dist\index.js' at Error (native)
```

**Comment by sfaizanh** [comment]
@arielfaur appreciated for replying, can you run delete that line from your tsconfig.json file `"files": [ "node_modules/ionic-audio/dist/index.ts" ]` and goto C:\Users\ariel\Projects\test-audio\node_modules\ionic-audio folder and run

**npm run prepublish** 

It should work, the reason is that it doesn't ran that command after fetching from github as you can check this issue on npm repository [run `prepublish` for git url packages](https://github.com/npm/npm/issues/3055).

NPM package manager runs this command when you publish your package or if you don't want to add the transpiled files in your package then you have to replace 

```"prepublish": "tsc -p ./",``` in package.json with 

```
"build": "npm run compile:ts",
"compile:ts": "tsc -p ./"
```

Awaiting for your reply.

**Comment by borodiliz** [comment]
@sfaizanh I'm testing your branch with the following steps:

* Update **package.json** to:
```
   "ionic-audio": "git+https://github.com/sfaizanh/ionic-audio.git#2.0",
```
* Remove the following lines from **tsconfig.json**:
```
 "files": [
    "node_modules/ionic-audio/dist/index.ts"
  ]
```
* Run prepublish script:
```
cd node_modules\ionic-audio 
npm run prepublish
```

### Results (Tested on a real Android device): 

* No problem building or running app when I build using `dev` environment  `ionic build android --dev`
* On production environment ( `ionic build android --prod --release` ), no errors building but I get the following error when trying to run the app:

```
02-27 17:07:52.141 32664 32664 I chromium: [INFO:CONSOLE(25)] "ORIGINAL STACKTRACE:", source: file:///android_asset/www/build/main.js?ionicCachebuster=59891 (25)
02-27 17:07:52.142 32664 32664 I chromium: [INFO:CONSOLE(25)] "Error: No provider for t!
02-27 17:07:52.142 32664 32664 I chromium:     at e [as constructor] (file:///android_asset/www/build/main.js?ionicCachebuster=59891:8:10870)
02-27 17:07:52.142 32664 32664 I chromium:     at e [as constructor] (file:///android_asset/www/build/main.js?ionicCachebuster=59891:31:19906)
02-27 17:07:52.142 32664 32664 I chromium:     at new e (file:///android_asset/www/build/main.js?ionicCachebuster=59891:31:20233)
02-27 17:07:52.142 32664 32664 I chromium:     at t._throwOrNull (file:///android_asset/www/build/main.js?ionicCachebuster=59891:50:2880)
02-27 17:07:52.142 32664 32664 I chromium:     at t._getByKeyDefault (file:///android_asset/www/build/main.js?ionicCachebuster=59891:50:3236)
02-27 17:07:52.142 32664 32664 I chromium:     at t._getByKey (file:///android_asset/www/build/main.js?ionicCachebuster=59891:50:2790)
02-27 17:07:52.142 32664 32664 I chromium:     at t.get (file:///android_asset/www/build/main.js?ionicCachebuster=59891:49:31207)
02-27 17:07:52.142 32664 32664 I chromium:     at e.get (file:///android_asset/www/build/main.js?ionicCachebuster=59891:25:12482)
02-27 17:07:52.142 32664 32664 I chromium:     at e.t.injectorGet (file:///android_asset/www/build/main.js?ionicCachebuster=59891:2:6975)
02-27 17:07:52.142 32664 32664 I chromium:     at e.get (file:///android_asset/www/build/main.js?ionicCachebuster=59891:50:5499)", source: file:///android_asset/www/build/main.js?ionicCachebuster=59891 (25)

```

**Comment by sfaizanh** [comment]
@borodiliz I have tested the app on real iOS device it works fine, haven't tested on Android device

**Comment by borodiliz** [comment]
Thanks @sfaizanh 

**Tests done:**

`ionic build android --release` : OK
`ionic build android --prod --release` : FAIL . Error: `Uncaught Error: No provider for t!`
`ionic build android --aot` : FAIL . Error: `Uncaught Error: No provider for Config!`
`ionic build android --dev --aot` : FAIL . Error:
```
02-28 13:32:30.132 29050 29050 I chromium: [INFO:CONSOLE(64984)] "Error: No provider for Config!
02-28 13:32:30.132 29050 29050 I chromium:     at NoProviderError.BaseError [as constructor] (file:///android_asset/www/build/main.js?ionicCachebuster=67380:21989:34)
02-28 13:32:30.132 29050 29050 I chromium:     at NoProviderError.AbstractProviderError [as constructor] (file:///android_asset/www/build/main.js?ionicCachebuster=67380:81326:16)
02-28 13:32:30.132 29050 29050 I chromium:     at new NoProviderError (file:///android_asset/www/build/main.js?ionicCachebuster=67380:81357:16)
02-28 13:32:30.132 29050 29050 I chromium:     at ReflectiveInjector_._throwOrNull (file:///android_asset/www/build/main.js?ionicCachebuster=67380:131549:19)
02-28 13:32:30.132 29050 29050 I chromium:     at ReflectiveInjector_._getByKeyDefault (file:///android_asset/www/build/main.js?ionicCachebuster=67380:131577:25)
02-28 13:32:30.132 29050 29050 I chromium:     at ReflectiveInjector_._getByKey (file:///android_asset/www/build/main.js?ionicCachebuster=67380:131540:25)
02-28 13:32:30.132 29050 29050 I chromium:     at ReflectiveInjector_.get (file:///android_asset/www/build/main.js?ionicCachebuster=67380:131349:21)
02-28 13:32:30.132 29050 29050 I chromium:     at AppModuleInjector.NgModuleInjector.get (file:///android_asset/www/build/main.js?ionicCachebuster=67380:65291:52)
02-28 13:32:30.132 29050 29050 I chromium:     at View_IonicApp0.AppView.injectorGet (file:///android_asset/www/build/main.js?ionicCachebuster=67380:3447:45)
02-28 13:32:30.132 29050 29050 I chromium:     at ElementInjector.get (file:///android_asset/www/build/main.js?ionicCachebuster=67380:131747:27)", source: file:///android_asset/www/build/main.js?ionicCachebuster=67380 (64984)

```

**My conclusions:**
* AoT is  causing the problem
* The `--prod` tag also causes the problem, but the error is different due to uglify / minify tasks

**My `imports []` :**
```
  imports: [
    IonicModule.forRoot(MyApp),
    CloudModule.forRoot(cloudSettings),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    }),
    ElasticModule,
    IonicAudioModule.forRoot()
  ],
```

**Comment by sfaizanh** [comment]
Hi @borodiliz can you download this [branch](https://github.com/sfaizanh/ionic-audio/tree/demo) 

**After download and extracting tar file**

```npm install```

**Run prepublish script:**
```
cd node_modules\ionic-audio 
npm run prepublish
```

**Add Android Platform**
```
ionic add platform android
```

**Build**
```
ionic build android --prod --release
```

----

If that works then delete the **ionic-audio** from your **Project**
```
rm -r project/node_modules/ionic-audio  (rm: OSX or Linux | -r recursive)
```

***Back to main project directory***
```npm install```

**Build**
```
ionic build android --prod --release
```

**Comment by borodiliz** [comment]
Thanks @sfaizanh 

Your demo application works perfectly with AoT!

After further investigation and tests, the problem was in **my** application. Downgrading `ionic-angular` from `2.1.0` to `2.0.1` solves the problem. 

I suppose there is a conflict because `ionic-audio` depends on `ionic-angular` `2.0.1`. Is there a way to avoid this so we can use `ionic-audio` with latest versions of `ionic-angular`?

@arielfaur I confirm this branch is working on  Android 7.1.1 and 4.4.4 with AoT

Thanks all for your time

**Comment by sfaizanh** [comment]
Ok i'll test with current version of Ionic (2.1.0)

**Comment by sfaizanh** [comment]
Thanks @borodiliz for confirmation and testing on android, I have tested on iOS (10.2.1) with ionic 2.1.0 it works fine and i have also update the `package.json` for angular version. (main and demo)

You can install with your project

**Update package.json**
```
"ionic-angular": "2.1.0",
"ionic-audio": "git+https://github.com/sfaizanh/ionic-audio.git#2.0",
```

Delete **`ionic-audio`** folder in **`node_modules/`**

Install package again
```
npm install
```

**Run prepublish script:**
```
cd node_modules\ionic-audio 
npm run prepublish
```
**Build**
```
ionic build android --prod --release
```

Now i'm waiting for @arielfaur confirmation if he merges this pull request or not, so we can remove 
`"ionic-audio": "git+https://github.com/sfaizanh/ionic-audio.git#2.0",` with `"ionic-audio": "2.3.2",` and get rid of `npm run prepublish`

Currently ionic team is working **[2.2.0](https://github.com/driftyco/ionic/milestone/51)** and soon **[2.3.0](https://github.com/driftyco/ionic/tree/2.4.8-angular)** with **Angular 2.4.8** support 
Angular Team are working on **[Angular 4](https://github.com/angular/angular/milestone/72)** 

@arielfaur I have also updated the demo with **ionic 2.1.0** You have to change package.json

**`"ionic-audio": "git+https://github.com/sfaizanh/ionic-audio.git#2.0",`** with **`"ionic-audio": "2.3.2",`** or whatever version you going to

**Comment by arielfaur** [comment]
Hi @borodiliz and @sfaizanh ! I kind of got lost following all the changes here. Thanks a lot for your efforts. I think the lack of documentation in this area regarding Angular 2, AoT and component development really suck. There are no clear guidelines. It is all trial and error.

**Comment by arielfaur** [comment]
In the meantime we will have to manually tweak when necessary in order to make this thing work in every scenario.

**Comment by arielfaur** [comment]
@sfaizanh I just tested this and worked fine with the ```prod``` flag. I just merged it.

**Comment by arielfaur** [comment]
I am thinking we should probably ship the module with the transpiled files to avoid the issues with ```npm run prepublish```. Otherwise users of this module will need to run it manually, right?

**Comment by arielfaur** [comment]
I can confirm that installing the module on a fresh Ionic project requires me to manually run ```npm run prepublish``` otherwise it breaks. Any workaround for this?

**Comment by sfaizanh** [comment]
@arielfaur Thanks for merging and sorry for delay response please read this [article](https://medium.com/@OCombe/how-to-publish-a-library-for-angular-2-on-npm-5f48cdabf435)

**Comment by sfaizanh** [comment]
@arielfaur You have to run prepublish on your machine before publishing and Please add .npmignore file in main directory 

```
# Node generated files
node_modules
npm-debug.log
# OS generated files
Thumbs.db
.DS_Store
# Ignored files
*.ts
!*.d.ts
```

**Comment by sfaizanh** [comment]
@arielfaur you can **unpublish** the current version from NPM 
```
npm unpublish ionic-audio@2.3.2
```

[See this article ](https://docs.npmjs.com/cli/unpublish)

**Comment by sfaizanh** [comment]
@arielfaur in package.json
Replace this
```
  "scripts": {
    "prepublish": "tsc -p ./",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```
with

```
  "scripts": {
    "prepublish": "tsc -p ./",
    "release": "npm run prepublish && npm publish",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

After that when your are publishing then simply run 
```
npm run release
```

it will do both transpile and publish to NPM server

**Note : Don't forget to add (.npmignore) file** 

```
# Node generated files
node_modules
npm-debug.log
# OS generated files
Thumbs.db
.DS_Store
# Ignored files
*.ts
!*.d.ts
```
---
@arielfaur If you want me to do it, I love to i'll submit a PR in 10min please do let me know.

Thanks

**Comment by arielfaur** [comment]
Thanks @sfaizanh. It works now! I just published version ```2.3.3```

**Comment by sfaizanh** [comment]
@arielfaur It works fine but there is an issue in demo. All the .ts files are ignored, if you don't want the demo in npm please add **demo** in **.npmignore**

Thanks for your time

**Comment by arielfaur** [comment]
What do you mean exactly? I tested the demo project and works fine on my end.

**Comment by sfaizanh** [comment]
@arielfaur Go to anywhere in PC like **Documents**

```
mkdir test-ionic-audio
cd test-ionic-audio
npm init
npm install ionic-audio
```

**Comment by sfaizanh** [comment]
You can simple add `demo` after `node_modules` in **.npmignore** to ignore the confusion 

_Ignoring **demo** folder in NPM package_

**Comment by arielfaur** [comment]
I followed the classic use case: creating a fresh ionic project, installing ionic-audio from npm and adding dependencies. It all works as expected with ```ionic serve``` but again fails with a production build 😢 

capture

Any ideas?

**Comment by sfaizanh** [comment]
@arielfaur Maybe, there is an issue with lambda functions in Angular 2, try this one go to `/src/app/app.module.ts`
```
  imports: [
    IonicModule.forRoot(MyApp),
    IonicAudioModule.forRoot({ provide: AudioProvider, useFactory: audioProviderFactory }), 
  ],
```

```
  imports: [
    IonicModule.forRoot(MyApp),
    IonicAudioModule.forRoot(), 
  ],
```

Or if you have ng2-translate this one got the same issue, Hope it helps

@arielfaur did you build **demo** or **new project**?

**Comment by sfaizanh** [comment]
Just found the bug remove this **`*.ts`** from your **`.npmignore`**  and republish to NPM

What step did i took

```
ionic start --v2 newtestapp tabs
npm i ionic-audio
copied my `dist` folder `node_modules/ionic-audio/dist`
```

It works, mainly because .ts files are required by AOT Compiler

**Comment by arielfaur** [comment]
@sfaizanh Works like a charm! Thanks. Can you give version ```2.3.4``` a last try to check it works on your end too? I tried the same use case, running a production build worked perfectly.

**Comment by sfaizanh** [comment]
@arielfaur Build Success and running on iOS Device

**Comment by sfaizanh** [comment]
@arielfaur One more thing 
[http://arielfaur.github.io/ionic-audio/2.0/index.html](http://arielfaur.github.io/ionic-audio/2.0/index.html) you have to update the document

```
import { IonicAudioModule } from 'ionic-audio/dist';
```
to 
```
import { IonicAudioModule } from 'ionic-audio';
```
and more below in document

**Comment by arielfaur** [comment]
Done! Thanks.

**Pull request merged**
