### PR TITLE
Ionic 2.2.0 Support

### PR DESCRIPTION
**Pull request by sfaizanh**
Update dependencies
Added Readme and License.md files
Fixed AOT issue in ionic-audio-web-track.ts

### CODE REVIEW

**Comment by sfaizanh** [comment]
@arielfaur any update?

**Comment by arielfaur** [comment]
Hi @sfaizanh I have merged your PR and am testing but I still get build errors with the `-prod` flag. Any ideas?

capture

**Comment by sfaizanh** [comment]
Hi @arielfaur, i'm in middle of something i'll update you in an hour

**Comment by sfaizanh** [comment]
Hi @arielfaur, It works fine **"Build Success"** may be you haven't change the ionic audio in `demo/package.json`

`cd demo`
`"ionic-audio": "^2.3.4"` to `"ionic-audio": "git+https://github.com/sfaizanh/ionic-audio.git#2.0"
`
`rm -r node_modules (remove node_modules)`
`npm i`
`cd node_modules/ionic-audio`
`npm run prepublish`

then in project directory 
`ionic build ios --release --prod` or `ionic build android --release --prod`

My apologies for the delay

**Comment by sfaizanh** [comment]
@arielfaur i have removed dependencies and added to devDependencies so that users will not affects on ionic-version update 81da41b0ecaddc73d7f7bf832a0b3c8a465f15bc

**Comment by sfaizanh** [comment]
@arielfaur if you are merging #101 pull request then merge it first then i'll update it so that this pull can be merged with no conflicts

**Comment by borodiliz** [comment]
Thanks @arielfaur . Works fine on `ionic 2.3.`0 and buiding with `--prod` ( AoT )

**Comment by codinronan** [comment]
Thank you guys for this! Now that AoT build works my app startup time is like 2 seconds (down from 10!!). Amazing!

**Comment by sfaizanh** [comment]
I would say Merge #101 i have to update the code so that we don't have merge issue

**Comment by sfaizanh** [comment]
Hi @arielfaur Angular 4 showing some warnings.

```
Warning: Can't resolve all parameters for WebAudioTrack in 
/Users/faizanhasan/Documents/v2/node_modules/ionic-audio/dist/ionic-audio-web-track.ts: (?, ?). 
This will become an error in Angular v5.x
```
```
Warning: Can't resolve all parameters for CordovaAudioTrack in 
/Users/faizanhasan/Documents/v2/node_modules/ionic-audio/dist/ionic-audio-cordova-track.ts: (?).
This will become an error in Angular v5.x
```

**Pull request closed without merging**
